//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18449
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShedWeb.ShedService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShedService.ShedServiceSoap")]
    public interface ShedServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/upLoadData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string upLoadData(string nID, string dataType, string dataInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendCommand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool sendCommand();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/receiveCommand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool receiveCommand();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/clearCommand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool clearCommand();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getExceptionRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getExceptionRecord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLogInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getLogInfo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShedServiceSoapChannel : ShedWeb.ShedService.ShedServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShedServiceSoapClient : System.ServiceModel.ClientBase<ShedWeb.ShedService.ShedServiceSoap>, ShedWeb.ShedService.ShedServiceSoap {
        
        public ShedServiceSoapClient() {
        }
        
        public ShedServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShedServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShedServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShedServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string upLoadData(string nID, string dataType, string dataInfo) {
            return base.Channel.upLoadData(nID, dataType, dataInfo);
        }
        
        public string getData() {
            return base.Channel.getData();
        }
        
        public bool sendCommand() {
            return base.Channel.sendCommand();
        }
        
        public bool receiveCommand() {
            return base.Channel.receiveCommand();
        }
        
        public bool clearCommand() {
            return base.Channel.clearCommand();
        }
        
        public string getExceptionRecord() {
            return base.Channel.getExceptionRecord();
        }
        
        public string getLogInfo() {
            return base.Channel.getLogInfo();
        }
    }
}
